static const char black[]       = "#1e222a";
static const char gray2[]       = "#2e323a"; // unfocused window border
static const char gray3[]       = "#545862";
static const char gray4[]       = "#6d8dad";
static const char gray5[]       = "#c1c1a8";
static const char blue[]        = "#7aa2f7"; // focused window border
static const char green[]       = "#98C379";
static const char red[]         = "#E06C75";
static const char orange[]      = "#E49263";
static const char yellow[]      = "#E5C07B";
static const char pink[]        = "#E98CA4";
static const char purple[]      = "#C678DD";
static const char purple_hypr[] = "#9C61B1";
static const char cyan[]        = "#56B6C2";
static const char col_borderbar[]  = "#1e222a"; // inner border
//
// static const char black[]       = "#040406";
// static const char gray2[]       = "#424244"; // unfocused window border
// static const char gray3[]       = "#818182";
// static const char gray4[]       = "#c0c0c0";
// static const char blue[]        = "#F38BA8"; // focused window border
// static const char green[]       = "#74BEDF";
// static const char red[]         = "#A3728B";
// static const char orange[]      = "#ba8566";
// static const char yellow[]      = "#F9B288";
// static const char pink[]        = "#E6D1B6";
// static const char purple[]      = "#ac9c88";
// static const char purple_hypr[] = "#9C61B1";
// static const char cyan[]        = "#8CB2F7";
// static const char col_borderbar[]  = "#040406"; // inner border
//
